# Generated by Django 5.2.12 on 2026-05-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('novios', 'Plan Novios'), ('eventos', 'Plan Eventos'), ('decoradores', 'Inscripción Decoradores'), ('restaurantes', 'Restaurantes'), ('casa_nueva', 'Casa Nueva')], max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('titulo_terminos', models.CharField(default='Términos', max_length=200)),
                ('contenido_terminos', models.TextField(blank=True)),
                ('titulo_beneficios', models.CharField(default='Beneficios', max_length=200)),
                ('contenido_beneficios', models.TextField(blank=True)),
                ('texto_boton_principal', models.CharField(blank=True, max_length=100)),
                ('url_boton_principal', models.CharField(blank=True, max_length=200)),
                ('texto_boton_secundario', models.CharField(blank=True, max_length=100)),
                ('url_boton_secundario', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='SeccionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='planes.plan')),
            ],
            options={
                'verbose_name': 'Sección del Plan',
                'verbose_name_plural': 'Secciones del Plan',
                'ordering': ['orden'],
            },
        ),
    ]
