# Generated by Django 5.2.12 on 2026-05-11 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliadoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la marca')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='aliados/', verbose_name='Logo (se procesará a fondo blanco)')),
                ('categoria', models.CharField(choices=[('hoteles', 'Hoteles'), ('eventos_flores', 'Eventos y Flores'), ('fotografia', 'Fotografía'), ('bakery', 'Bakery / Pastelería'), ('spa_belleza', 'Spa & Belleza'), ('viajes', 'Viajes'), ('musica', 'Música / DJ'), ('vestimenta', 'Vestimenta & Moda'), ('decoracion', 'Decoración'), ('gastronomia', 'Gastronomía / Bar'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Categoría')),
                ('descripcion_beneficio', models.TextField(help_text='Ej: 10% de descuento en todos los servicios...', verbose_name='Descripción del beneficio')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('instagram', models.CharField(blank=True, help_text='Solo el nombre de usuario, ej: liven.home.decor', max_length=100, null=True, verbose_name='Instagram (sin @)')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aliado / Beneficio',
                'verbose_name_plural': 'Aliados / Beneficios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanNovios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombre(s) de los novios')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email de acceso')),
                ('clave', models.CharField(max_length=128, verbose_name='Clave de acceso (hash)')),
                ('fecha_boda', models.DateField(blank=True, null=True, verbose_name='Fecha de la boda')),
                ('saldo_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo acumulado ($)')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Novios',
                'verbose_name_plural': 'Planes de Novios',
            },
        ),
        migrations.CreateModel(
            name='MovimientoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aporte', 'Aporte'), ('anticipo', 'Anticipo'), ('devolucion', 'Devolución'), ('ajuste', 'Ajuste')], default='aporte', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='planes.plannovios')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
