# Generated by Django 5.2.12 on 2026-05-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_aliadobeneficio_plannovios_movimientoplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPlanNovios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_novios', models.CharField(max_length=255, verbose_name='Nombres de los Novios')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono / WhatsApp')),
                ('fecha_boda', models.DateField(verbose_name='Fecha tentativa de boda')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('mensaje', models.TextField(blank=True, verbose_name='Comentario adicional')),
                ('procesado', models.BooleanField(default=False, verbose_name='¿Ya se contactó?')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Plan',
                'verbose_name_plural': 'Solicitudes de Planes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
