# Generated by Django 5.2.12 on 2026-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_solicitudplannovios'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudplannovios',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('finalizado', 'Finalizado')], default='pendiente', help_text='Solo los planes "Aprobados" aparecen en la lista pública.', max_length=20, verbose_name='Estado'),
        ),
    ]
