# Generated by Django 5.2.12 on 2026-05-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_solicitud_estado_field'),
        ('productos', '0010_alter_marca_imagen_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudplannovios',
            name='productos_regalo',
            field=models.ManyToManyField(blank=True, to='productos.producto', verbose_name='Productos elegidos como regalo'),
        ),
    ]
