# Generated by Django 5.2.12 on 2026-05-13 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_solicitudplannovios_productos_regalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudplannovios',
            name='clave',
            field=models.CharField(blank=True, max_length=128, verbose_name='Clave Portal (Hash)'),
        ),
        migrations.AddField(
            model_name='solicitudplannovios',
            name='saldo_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Acumulado ($)'),
        ),
        migrations.AlterField(
            model_name='movimientoplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='planes.solicitudplannovios'),
        ),
    ]
