# Generated by Django 5.2.12 on 2026-05-15 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0006_solicitudplannovios_clave_and_more'),
        ('productos', '0010_alter_marca_imagen_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoplan',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Si es un abono a un producto específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_plan', to='productos.producto'),
        ),
    ]
