# Generated by Django 5.2.12 on 2026-06-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0007_movimientoplan_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudplannovios',
            name='foto_pareja',
            field=models.ImageField(blank=True, help_text='Foto que se mostrará en la página para dejar regalos (en lugar de la tarjeta azul por defecto)', null=True, upload_to='planes/parejas/', verbose_name='Foto de la Pareja'),
        ),
    ]
