# Generated by Django 5.2.12 on 2026-06-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0008_solicitudplannovios_foto_pareja'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudplannovios',
            name='apellidos_novios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos de los Novios'),
        ),
    ]
