# Generated by Django 5.2.12 on 2026-06-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0009_solicitudplannovios_apellidos_novios'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudplannovios',
            name='monto_minimo_regalo',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Monto mínimo que se puede regalar en efectivo.', max_digits=10, verbose_name='Monto Mínimo de Regalo ($)'),
        ),
    ]
