# Generated by Django 5.2.12 on 2026-04-21 07:00

import apps.productos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Material, País de origen, Peso', max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('posicion', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'ordering': ['posicion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/')),
                ('posicion', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el menú')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['posicion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa de la colección', null=True, upload_to='colecciones/')),
                ('activo', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False, help_text='Mostrar en página principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medio', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default='imagen', max_length=10)),
                ('imagen', models.ImageField(blank=True, help_text='JPG, PNG, GIF, WebP, HEIC', null=True, upload_to='productos/imagenes/', validators=[apps.productos.models.validate_image_extension])),
                ('video', models.FileField(blank=True, help_text='MP4, WebM, MOV', null=True, upload_to='productos/videos/', validators=[apps.productos.models.validate_video_extension])),
                ('url', models.TextField(blank=True, default='', help_text='URL alternativa si no se sube archivo')),
                ('posicion', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('es_principal', models.BooleanField(default=False, help_text='Imagen principal del producto')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Imagen/Video',
                'verbose_name_plural': 'Imágenes/Videos',
                'ordering': ['-es_principal', 'posicion', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion_corta', models.TextField(blank=True, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Si tiene precio de oferta, ingrésalo aquí', max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('dimensiones', models.CharField(blank=True, help_text='Ej: 30cm x 20cm x 10cm', max_length=200, null=True)),
                ('material', models.CharField(blank=True, help_text='Ej: Cerámica, Madera, Vidrio', max_length=200, null=True)),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en página principal')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del ícono (opcional)', max_length=50)),
                ('dias_devolucion', models.PositiveIntegerField(default=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Política de Devolución',
                'verbose_name_plural': 'Políticas de Devolución',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Shipping & Delivery', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción general de la política de envío')),
                ('tiempo_nacional', models.CharField(blank=True, help_text='Ej: 3-6 días', max_length=100)),
                ('tiempo_internacional', models.CharField(blank=True, help_text='Ej: 12-26 días', max_length=100)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('envio_gratis_desde', models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo para envío gratis', max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Información de Envío',
                'verbose_name_plural': 'Información de Envío',
            },
        ),
        migrations.CreateModel(
            name='AtributoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Ej: Cerámica, Hecho a mano, México', max_length=200)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_producto', to='productos.atributo')),
            ],
            options={
                'verbose_name': 'Atributo del Producto',
                'verbose_name_plural': 'Atributos del Producto',
                'ordering': ['atributo__posicion'],
            },
        ),
    ]
