# Generated by Django 5.2.12 on 2026-04-21 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Déjalo vacío si es una categoría principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='productos.categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='coleccion',
            field=models.ForeignKey(blank=True, help_text='Colección a la que pertenece esta categoría (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='productos.coleccion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='coleccion',
            field=models.ForeignKey(blank=True, help_text='Colección a la que pertenece este producto (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.coleccion'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='atributoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='productos.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('usuario', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='atributoproducto',
            unique_together={('producto', 'atributo')},
        ),
    ]
