# Generated by Django 5.2.12 on 2026-04-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(verbose_name='URL de Instagram')),
                ('thumbnail_url', models.URLField(verbose_name='URL de la imagen')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop Gram Post',
                'verbose_name_plural': 'Shop Gram Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
