# Generated by Django 5.2.12 on 2026-04-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_shopgrampost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopgrampost',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='shopgrampost',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='shopgram/', verbose_name='Imagen'),
        ),
    ]
