# Generated by Django 5.2.12 on 2026-04-28 03:56

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def forwards_migrate_brand_data(apps, schema_editor):
    Producto = apps.get_model('productos', 'Producto')
    Marca = apps.get_model('productos', 'Marca')

    for producto in Producto.objects.all().iterator():
        marca_texto = (getattr(producto, 'marca', '') or '').strip()
        if not marca_texto:
            continue

        base_slug = slugify(marca_texto)
        slug = base_slug
        counter = 1
        while Marca.objects.filter(slug=slug).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1

        marca_obj, _ = Marca.objects.get_or_create(
            nombre=marca_texto,
            defaults={'slug': slug},
        )

        if not marca_obj.slug:
            marca_obj.slug = slug
            marca_obj.save(update_fields=['slug'])

        producto.marca_tmp_id = marca_obj.pk
        producto.save(update_fields=['marca_tmp'])


def backwards_migrate_brand_data(apps, schema_editor):
    Producto = apps.get_model('productos', 'Producto')

    for producto in Producto.objects.select_related('marca_tmp').all().iterator():
        producto.marca = producto.marca_tmp.nombre if producto.marca_tmp_id else ''
        producto.save(update_fields=['marca'])


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_shopgrampost_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion_larga',
            new_name='descripcion_completa',
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso del producto en kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca_tmp',
            field=models.ForeignKey(blank=True, help_text='Marca comercial asociada a este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.marca'),
        ),
        migrations.RunPython(forwards_migrate_brand_data, backwards_migrate_brand_data),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca_tmp',
            new_name='marca',
        ),
    ]
