# Generated by Django 5.2.12 on 2026-04-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, help_text='Marca comercial asociada a este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.marca'),
        ),
    ]
