# Generated by Django 5.2.12 on 2026-05-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='capacidad',
            field=models.CharField(blank=True, help_text='Ej: 50 ml, 1 Litro, 500 gramos', max_length=200, null=True),
        ),
    ]
