# Generated by Django 5.2.12 on 2026-05-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_capacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='coleccion',
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen_slider',
            field=models.ImageField(blank=True, help_text='Imagen especial para el slider si está activo', null=True, upload_to='marcas/slider/'),
        ),
        migrations.AddField(
            model_name='marca',
            name='mostrar_en_slider',
            field=models.BooleanField(default=False, help_text='¿Mostrar esta marca en el slider principal del home?'),
        ),
    ]
