# Generated by Django 5.2.12 on 2026-05-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_categoria_coleccion_marca_imagen_slider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='imagen_slider',
            field=models.ImageField(blank=True, help_text="Imagen especial para el slider del home (solo se usa si 'mostrar en slider' está marcado)", null=True, upload_to='marcas/slider/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='mostrar_en_slider',
            field=models.BooleanField(default=False, help_text='¿Mostrar esta marca en el slider del home?'),
        ),
    ]
