# Generated by Django 5.2.12 on 2026-05-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_marca_imagen_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='es_promocion',
            field=models.BooleanField(default=False, help_text='Marcar si es una promoción/novedad (Día del Padre, San Valentín, etc.)'),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='texto_anuncio',
            field=models.CharField(blank=True, help_text='Texto que aparece en la barra de anuncios superior', max_length=200, null=True),
        ),
    ]
