# Generated by Django 5.2.12 on 2026-05-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_coleccion_es_promocion_coleccion_texto_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='imagen_slider_movil',
            field=models.ImageField(blank=True, help_text="Imagen especial para el slider del home en versión celular/móvil (solo se usa si 'mostrar en slider' está marcado)", null=True, upload_to='marcas/slider_movil/'),
        ),
    ]
