# Generated by Django 5.2.12 on 2026-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_marca_imagen_slider_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Código SKU del producto', max_length=100, null=True, unique=True),
        ),
    ]
