# Generated by Django 5.2.12 on 2026-06-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='payphone_authorization_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='payphone_client_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='payphone_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='payphone_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
