# Generated by Django 5.2.12 on 2026-06-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_pedido_estado_pago_and_more'),
        ('productos', '0014_tiendaconfig'),
    ]

    operations = [
    ]
