# Generated by Django 5.2.12 on 2026-06-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_merge_20260608_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='orden_slider',
            field=models.PositiveIntegerField(default=0, help_text='Posición de aparición en el slider del home. Si hay colisión, las demás se desplazan automáticamente.', verbose_name='Orden en el Slider'),
        ),
    ]
