# Generated by Django 5.2.12 on 2026-06-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_merge_20260608_2129'),
        ('productos', '0016_marca_orden_slider'),
    ]

    operations = [
    ]
