# Generated by Django 5.2.12 on 2026-06-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_merge_20260609_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendaconfig',
            name='cuenta_bancaria',
            field=models.TextField(blank=True, default='Banco Pichincha\nCuenta Ahorros: 2200000000\nNombre: Liven Tienda\nCI: 1111111111', help_text='Información de la cuenta bancaria para transferencias', null=True, verbose_name='Datos de Cuenta Bancaria'),
        ),
    ]
