# Generated by Django 5.2.12 on 2026-06-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_tiendaconfig_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comportamiento_agotamiento',
            field=models.CharField(blank=True, choices=[('CAMBIAR_A_BAJO_PEDIDO', 'Cambiar a Bajo Pedido al agotarse'), ('DESACTIVAR', 'Desactivar producto al agotarse')], help_text='Acción automática cuando el stock llega a 0 (solo para Entrega Inmediata).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_inventario',
            field=models.CharField(choices=[('BAJO_PEDIDO', 'Bajo Pedido'), ('ENTREGA_INMEDIATA', 'Entrega Inmediata')], default='BAJO_PEDIDO', help_text='Bajo Pedido: disponible siempre, sin control de stock. Entrega Inmediata: stock físico controlado.', max_length=30),
        ),
    ]
