# Generated by Django 5.2.12 on 2026-06-16 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_producto_comportamiento_agotamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDestacadoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField(help_text='Posición en el carrusel del home (1-12).', unique=True)),
                ('producto', models.ForeignKey(help_text='Producto que aparecerá en esta posición.', on_delete=django.db.models.deletion.CASCADE, related_name='destacado_home', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Producto destacado en Home',
                'verbose_name_plural': 'Productos destacados en Home',
                'ordering': ['posicion'],
            },
        ),
    ]
