# Generated by Django 5.2.12 on 2026-06-16 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_productodestacadohome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDestacadoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField(help_text='Posición en el carrusel de esa marca (1-12).')),
                ('marca', models.ForeignKey(help_text='Marca a la que pertenece esta selección.', on_delete=django.db.models.deletion.CASCADE, related_name='productos_destacados_home', to='productos.marca')),
                ('producto', models.ForeignKey(help_text='Producto que aparecerá en esta posición.', on_delete=django.db.models.deletion.CASCADE, related_name='destacado_marca_home', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Producto destacado por marca',
                'verbose_name_plural': 'Productos destacados por marca',
                'ordering': ['marca', 'posicion'],
                'unique_together': {('marca', 'posicion')},
            },
        ),
    ]
