# Generated by Django 5.2.12 on 2026-09-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_update_pedido_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendaconfig',
            name='modo_navidad',
            field=models.BooleanField(default=False, help_text='Activa el efecto de nieve en toda la tienda.', verbose_name='Modo Navidad (Nieve)'),
        ),
        migrations.AlterField(
            model_name='tiendaconfig',
            name='direccion',
            field=models.TextField(default='C.C Del Portal', verbose_name='Dirección de la Tienda'),
        ),
        migrations.AlterField(
            model_name='tiendaconfig',
            name='email',
            field=models.EmailField(default='liven_concept@outlook.com', max_length=254, verbose_name='Correo Electrónico de Contacto'),
        ),
        migrations.AlterField(
            model_name='tiendaconfig',
            name='horario_apertura',
            field=models.TextField(default='Lun-Vier 10am-8pm | Sáb 9am-7pm', verbose_name='Horario de Apertura'),
        ),
        migrations.AlterField(
            model_name='tiendaconfig',
            name='telefono',
            field=models.CharField(default='0995443335', max_length=50, verbose_name='Teléfono de Contacto'),
        ),
    ]
