# Generated by Django 5.2.12 on 2026-05-06 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0006_alter_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='portafolio/')),
                ('lado_imagen', models.CharField(choices=[('izquierda', 'Imagen a la izquierda'), ('derecha', 'Imagen a la derecha')], default='izquierda', help_text='¿La imagen va a la izquierda o derecha del texto?', max_length=10)),
                ('etiqueta', models.CharField(blank=True, help_text='Ej: PROYECTO 1', max_length=100)),
                ('posicion', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['posicion', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemLookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.DecimalField(decimal_places=2, default=50, help_text='Posición horizontal en % (0=izquierda, 100=derecha)', max_digits=5)),
                ('pos_y', models.DecimalField(decimal_places=2, default=50, help_text='Posición vertical en % (0=arriba, 100=abajo)', max_digits=5)),
                ('posicion', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookbook_items', to='productos.producto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portafolio.proyecto')),
            ],
            options={
                'verbose_name': 'Item Lookbook',
                'verbose_name_plural': 'Items Lookbook',
                'ordering': ['posicion'],
            },
        ),
    ]
