# Generated by Django 5.2.12 on 2026-05-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido', 'Pedido'), ('plan_novios', 'Plan de Novios')], max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación Admin',
                'verbose_name_plural': 'Notificaciones Admin',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
